GET http://localhost:8000 HTTP/1.1
###
POST http://localhost:8000/user/register HTTP/1.1
Content-Type: application/json

{
     "email": "naruto_uzumaki@gmail.com",
     "password": "password",
     "confirm": "password",
     "name": {
        "firstName": "Naruto",
        "middleName": "Namikaze",
        "lastName": "Uzumaki"
     },
     "bedrooms": 6,
     "propertyType": "semi-detached",
     "address": {
          "firstLine": "1 Windermere",
          "city": "Leicester",
          "postCode": "LE27GU"
     },
      "voucher": "72B432BD"
}

###

GET http://localhost:8000/user/ HTTP/1.1

### Login route
POST http://localhost:8000/user/login HTTP/1.1
Content-Type: application/json

{
     "email": "pinto_steve@yahoo.com",
     "password": "password"

}

###

POST http://localhost:8000/user/topup HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2FkYjRjODQ5MDYwN2EwMDllODQyOTgiLCJlbWFpbCI6Im5hcnV0b191enVtYWtpQGdtYWlsLmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzIzMjg1OTIsImV4cCI6MTY3MjMzMDM5Mn0.8QkJ7o2xTncmx9sAWMm73P4BuwqL71_gbXSTEBgsrYE
Content-Type: application/json

{
     "code": "32D10C6E"

}
### LogOut User

POST http://localhost:8000/user/logout HTTP/1.1

###
GET http://localhost:8000/user/reading HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2M0NWU5MWE0MmY3NGUxMjU3MzdmMzQiLCJlbWFpbCI6InBpbnRvX3N0ZXZlQHlhaG9vLmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzM4MTY1MDksImV4cCI6MTY3MzgxODMwOX0.5E_ZSQwgneCWe6D_Vlfjs2tQ4Vhf-7duL5gXwSpAv_c
###
POST http://localhost:8000/user/reading/new HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2FlYzliMmNhY2E5YzkwMWVlZjhiNTciLCJlbWFpbCI6InBpbnRvX3N0ZXZlQHlhaG9vLmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzIzOTkyOTUsImV4cCI6MTY3MjQwMTA5NX0.sMjJY1KJzM7Qw2dfX_prqS5abv20264bgZ6rfIxOAWk
Content-Type: application/json

{
     "dayReading": 1000,
	"nightReading": 1000,
	"gasReading": 1000,
     "date": "2023-1-30"
}

### Open API

GET http://localhost:8000/igse HTTP/1.1


### Admin login
POST http://localhost:8000/user/login HTTP/1.1
Content-Type: application/json

{
     "email": "gse@shangrila.gov.un",
     "password": "gse@energy"

}
### 
PUT  http://localhost:8000/igse/admin/tariff/update/standing HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2I5NzdjMmM2ZTU1NTNjYTM3ZGQ3ZjciLCJlbWFpbCI6ImdzZUBzaGFuZ3JpbGEuZ292LnVuIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjczMDk5MjEzLCJleHAiOjE2NzMxMDEwMTN9.DN2s0NasL14jjWrBTPzUTOrunhRPn0hCA2k3cj7QXBo
Content-Type: application/json

{
     "rate": 3.6
}

###

GET http://localhost:8000/igse/admin/voucher HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2FkYjRhZTQ5MDYwN2EwMDllODQyNDEiLCJlbWFpbCI6ImdzZUBzaGFuZ3JpbGEuZ292LnVuIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjcyMzI4NDMzLCJleHAiOjE2NzIzMzAyMzN9.LTwhvbm_PcQPFmNXC2AIKqQ3Cqnv3uNJAnj16Q15uPE
###
POST http://localhost:8000/igse/admin/voucher/new HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2FkYjRhZTQ5MDYwN2EwMDllODQyNDEiLCJlbWFpbCI6ImdzZUBzaGFuZ3JpbGEuZ292LnVuIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjcyMzI4NDk2LCJleHAiOjE2NzIzMzAyOTZ9.BoecB2PtobIxnbp6dFJG8Sl8PzDYp1MFicGDXUKPJ1U
Content-Type: application/json

{
     "code": "QRSTUVWx",
     "amount": 300
}

###
GET http://localhost:8000/igse/admin/voucher/XTX2GZAD HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2FkYmQ3M2UzMmZkMzYxM2RlMjI4NzEiLCJlbWFpbCI6ImdzZUBzaGFuZ3JpbGEuZ292LnVuIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjcyMzMwNjIxLCJleHAiOjE2NzIzMzI0MjF9.r4HlDZBGKCI6e0o0kTuOycKAkto2-8xN7yUaUvqccLk





### Login New User
POST http://localhost:8000/user/login HTTP/1.1
Content-Type: application/json

{
     "email": "naruto_uzumaki@gmail.com",
     "password": "password"

}

###

GET http://localhost:8000/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2I0YTgzM2E3NDY1MGY1Yzc5ZmYwNzIiLCJlbWFpbCI6ImdzZUBzaGFuZ3JpbGEuZ292LnVuIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjcyNzgzOTUzLCJleHAiOjE2NzI3ODU3NTN9.ePq1yoF96v0h3-diOIZUzoGa67MbJbrPHkQear93s14

###
GET http://localhost:8000/igse/tariff HTTP/1.1