GET http://localhost:8000 HTTP/1.1
###
POST http://localhost:8000/user/register HTTP/1.1
Content-Type: application/json

{
     "email": "naruto_uzumaki@gmail.com",
     "password": "password",
     "confirm": "password",
     "name": {
        "firstName": "Naruto",
        "middleName": "Namikaze",
        "lastName": "Uzumaki"
     },
     "bedrooms": 6,
     "propertyType": "semi-detached",
     "address": {
          "firstLine": "1 Windermere",
          "city": "Leicester",
          "postCode": "LE27GU"
     },
      "voucher": "XTX2GZAD"
}

###

GET http://localhost:8000/user/ HTTP/1.1

### Login route
POST http://localhost:8000/user/login HTTP/1.1
Content-Type: application/json

{
     "email": "pinto_steve@yahoo.com",
     "password": "password"

}

###

POST http://localhost:8000/user/topup HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2FkOGI0MzVhYmUxMjFhMTMzOTc5NzciLCJlbWFpbCI6InBpbnRvX3N0ZXZlQHlhaG9vLmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzIzMTc3ODIsImV4cCI6MTY3MjMxOTU4Mn0.w0-G2IU_1w94xMH7q53v5LyYGWZneq1_qIfCAK0IOW8
Content-Type: application/json

{
     "code": "32D10C6E"

}
### LogOut User

POST http://localhost:8000/user/logout HTTP/1.1

###
GET http://localhost:8000/user/reading HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2FkODhiZGZlNjk2ZTkxMjJiOTU2ZjMiLCJlbWFpbCI6Im5hcnV0b191enVtYWtpQGdtYWlsLmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzIzMTcxMjYsImV4cCI6MTY3MjMxODkyNn0.bN4V6CpxjJDJGU6CEsjw_j7x-huf7NJdfxY3uBIhOk8
###
POST http://localhost:8000/user/reading/new HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2FkODFlYTc4MDVjNmRiZmVlZDQxNzYiLCJlbWFpbCI6InBpbnRvX3N0ZXZlQHlhaG9vLmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzIzMTUzODEsImV4cCI6MTY3MjMxNzE4MX0.MXp0uZp9OG5kGoXE2TRVExPyUYXnkTsKMzvA5ws7KxI
Content-Type: application/json

{
     "dayReading": 100,
	"nightReading": 69,
	"gasReading": 420
}

### Open API

GET http://localhost:8000/igse HTTP/1.1


### Admin login
POST http://localhost:8000/user/login HTTP/1.1
Content-Type: application/json

{
     "email": "gse@shangrila.gov.un",
     "password": "gse@energy"

}

###
GET http://localhost:8000/igse/admin/tariff HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2FkOGUzNDY1MjhjMzZjMTdkMWE5YTciLCJlbWFpbCI6ImdzZUBzaGFuZ3JpbGEuZ292LnVuIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjcyMzE4NTQwLCJleHAiOjE2NzIzMjAzNDB9.QstkHF3nm9IHOXNKsEBhRnCQvgfnxSDmm0VwLrSynHI

###

GET http://localhost:8000/igse/admin/voucher HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2FkODZlZmQwMjZhMjM4YmJjOGRhYzgiLCJlbWFpbCI6ImdzZUBzaGFuZ3JpbGEuZ292LnVuIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjcyMzE2NzMwLCJleHAiOjE2NzIzMTg1MzB9.Z4hcN6LhVENjZ1ppoxHjMnyqlpl1W3mz1QG5-8M1fS8
###
POST http://localhost:8000/igse/admin/voucher/new HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2FkNzY4OTg3OGE0OTg5MmI5NWE3NjciLCJlbWFpbCI6ImdzZUBzaGFuZ3JpbGEuZ292LnVuIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjcyMzEyNDc4LCJleHAiOjE2NzIzMTQyNzh9.AW7CnBiRv-bBbsMSVFCTYaYjglcDW1dwHUZjzhXQBKk
Content-Type: application/json

{
     "code": "QRSTUVWx",
     "amount": 300
}

###
GET http://localhost:8000/igse/admin/voucher/XTX2GZAD HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2FjOGM0YjY1OGMyMWMwMTRiOWYxNzQiLCJlbWFpbCI6ImdzZUBzaGFuZ3JpbGEuZ292LnVuIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjcyMjUyNTM5LCJleHAiOjE2NzIyNTQzMzl9.j-8D1ZIzQnCwf5-v3lkX_EcMZE5nFu58r9uYbNigVH0
